apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd/application.yaml
  - ingress-nginx/application.yaml
  - cert-manager/application.yaml
  - external-dns/application.yaml
