#!/usr/bin/env sh
set -eu

: "${POSTGRES_USER:?POSTGRES_USER is required}"

DB_NAME="${POSTGRES_DB}"
QUEUE_DB_NAME="${POSTGRES_QUEUE_DB:-${POSTGRES_DB}_queue}"
CABLE_DB_NAME="${POSTGRES_CABLE_DB:-${POSTGRES_DB}_cable}"
TEST_DB_NAME="${POSTGRES_TEST_DB:-coffee_chatbot_test}"
TEST_QUEUE_DB_NAME="${POSTGRES_TEST_QUEUE_DB:-${TEST_DB_NAME}_queue}"
TEST_CABLE_DB_NAME="${POSTGRES_TEST_CABLE_DB:-${TEST_DB_NAME}_cable}"

for db_name in "$DB_NAME" "$QUEUE_DB_NAME" "$CABLE_DB_NAME" "$TEST_DB_NAME" "$TEST_QUEUE_DB_NAME" "$TEST_CABLE_DB_NAME"; do
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE ${db_name} TO ${POSTGRES_USER};
EOSQL
 done
