#!/usr/bin/env sh
set -eu

: "${POSTGRES_DB:?POSTGRES_DB is required}"

DB_NAME="${POSTGRES_DB}"
QUEUE_DB_NAME="${POSTGRES_QUEUE_DB:-${POSTGRES_DB}_queue}"
CABLE_DB_NAME="${POSTGRES_CABLE_DB:-${POSTGRES_DB}_cable}"
TEST_DB_NAME="${POSTGRES_TEST_DB:-coffee_chatbot_test}"
TEST_QUEUE_DB_NAME="${POSTGRES_TEST_QUEUE_DB:-${TEST_DB_NAME}_queue}"
TEST_CABLE_DB_NAME="${POSTGRES_TEST_CABLE_DB:-${TEST_DB_NAME}_cable}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
SELECT 'CREATE DATABASE ${DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${QUEUE_DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${QUEUE_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${CABLE_DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${CABLE_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${TEST_DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${TEST_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${TEST_QUEUE_DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${TEST_QUEUE_DB_NAME}')\gexec
SELECT 'CREATE DATABASE ${TEST_CABLE_DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${TEST_CABLE_DB_NAME}')\gexec
EOSQL
