apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - django
  - nextjs

labels:
  - pairs:
      app.kubernetes.io/part-of: coffee-chatbot
    includeSelectors: true
